language: node_js
node_js:
  - 12
script:
  - git clone https://github.com/ibm-garage-ref-storefront/inventory-ms-spring.git
  - cd ..
  - ls
  - npm run build
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_url: github.com
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: public
  on:
    branch: master
